name: tunetadka
description: "A Mp3 Music Player"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  just_audio_background: ^0.0.1-beta.17
  just_audio_windows: ^0.2.2
  flutter_animate: ^4.5.2
  file_picker: ^10.1.9
  path: ^1.9.1
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  marquee: ^2.3.0
  go_router: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/music_icon.png"
    icon_size: 180
  image_path: "assets/icon/music_icon.png"

flutter_native_splash:
  color: "#121212"
  image: assets/splash/splash_logo.png
  fullscreen: true
  android_12:
    image: assets/splash/splash_logo.png
    icon_background_color: "#121212"


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/splash/
